solver_options:
    regularization: 1e-3
    back_end: "qpoases"

stack:
    - ["Com"]
    - ["xtion"] # , "RightArm", "LeftArm"]
#    - ["Postural"]

constraints: ["JointLimits", "VelocityLimits", "LeftFoot", "RightFoot"]

xtion:
    lib_name: "libCartesioVisualServoing.so"
    type: "VisualServoing"
    distal_link: "camera_link"
    lambda:  0.002 # compare 0.002 and 0.0001
    feature_type: "vpFeaturePoint"
    number_of_features: 4


LeftFoot:
    type: "Cartesian"
    name: "left_foot"
    distal_link: "l_sole"

RightFoot:
    type: "Cartesian"
    name: "right_foot"
    distal_link: "r_sole"

LeftArm:
    type: "Cartesian"
    name: "left_hand"
    distal_link: "LSoftHand"
    base_link: "torso"
    lambda: 0.1

RightArm:
    type: "Cartesian"
    name: "right_hand"
    distal_link: "RSoftHand"
    base_link: "torso"
    lambda: 0.1

Postural:
    type: "Postural"
    lambda: 0.1
    weight:
        VIRTUALJOINT_1: 0.0
        VIRTUALJOINT_2: 0.0
        VIRTUALJOINT_3: 0.0
        VIRTUALJOINT_4: 0.0
        VIRTUALJOINT_5: 0.0
        VIRTUALJOINT_6: 0.0
        WaistYaw: 100.0

Com:
    type: "Com"
    lambda: 0.
    #indices: [0, 1]
    #weight: 10

JointLimits:
    type: "JointLimits"


VelocityLimits:
    type: "VelocityLimits"
