solver_options:
    regularization: 1e-3
    back_end: "qpoases"

stack:
    - ["camera_link"]
    - ["xtion"]
    - ["Postural"]

constraints: ["JointLimits", "VelocityLimits", "Com", "AngularMomentum"]

xtion:
    lib_name: "libCartesioVisualServoing.so"
    type: "VisualServoing"
    distal_link: "camera_link"
    lambda: 0.001
    feature_type: "vpFeaturePoint"
    number_of_features: 4

camera_link:
    type: "Cartesian"
    name: "camera_link"
    distal_link: "camera_link"
    indices: [0, 1, 2]
    lambda: 0.1

AngularMomentum:
    lib_name: "libCartesioAngularMomentumAddon.so"
    type: "AngularMomentum"
    
Postural:
    type: "Postural"
    lambda: 0.1
    weight:
        VIRTUALJOINT_1: 0.0
        VIRTUALJOINT_2: 0.0
        VIRTUALJOINT_3: 0.0
        VIRTUALJOINT_4: 0.0
        VIRTUALJOINT_5: 0.0
        VIRTUALJOINT_6: 0.0
        WaistYaw: 100.0

Com:
    type: "Com"
    lambda: 0.
#    indices: [0, 1]
#    weight: 10

JointLimits:
    type: "JointLimits"

VelocityLimits:
    type: "VelocityLimits"
