XBotCore:
  config_path: "/home/toto/catkin_ws/src/iit-coman-ros-pkg/coman_config/coman.yaml"

XBotInterface:
  urdf_path: "/home/toto/catkin_ws/src/iit-coman-ros-pkg/coman_urdf/urdf/coman.urdf"
  srdf_path: "/home/toto/catkin_ws/src/vsam/srdf/coman_space.srdf"
  joint_map_path: "/home/toto/catkin_ws/src/iit-coman-ros-pkg/coman_config/coman_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"
  
MasterCommunicationInterface:
  framework_name: "ROS"

XBotRTPlugins:
  plugins: ["HomingExample"] 
  io_plugins: []
  
NRTPlugins:
  plugins: [] 
  
TransmissionPlugins:
  plugins: [] 
  
WebServer:
  enable: "false"
  address: "127.0.0.1"
  port: "8081"

SimulationOptions:
  verbose_mode: "true"    
