solver_options:
    regularization: 1e-3
    back_end: "qpoases"

stack:
    - ["Com","LeftFoot", "RightFoot"]
    - ["xtion"]

constraints: ["JointLimits", "VelocityLimits"]

xtion:
    lib_name: "libCartesioVisualServoing.so"
    type: "VisualServoing"
    distal_link: "camera_link"
    lambda: 0.002 # compare 0.002 and 0.0001
    feature_type: "vpFeaturePoint"
    number_of_features: 4


LeftFoot:
    type: "Cartesian"
    name: "left_foot"
    distal_link: "l_sole"

RightFoot:
    type: "Cartesian"
    name: "right_foot"
    distal_link: "r_sole"

Com:
    type: "Com"
    lambda: 0.
#    #indices: [0, 1]
#    #weight: 10

JointLimits:
    type: "JointLimits"

VelocityLimits:
    type: "VelocityLimits"
